{% set name = "polartoolkit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polartoolkit-{{ version }}.tar.gz
  sha256: 4dfbff5fe41ef9fc64009a1d55b9fb9d6363f4e9cd5ca479689e4d2dfbbd416e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1 #RETURN THIS TO 0 ON NEXT RELEASE!!!
###
###
###
# RESET BUILD NUMBER
###
###
###
requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - pip
  run:
    - python >=3.9
    - pandas
    - openpyxl
    - pooch
    - verde >=1.8.0
    - xarray
    - harmonica >=0.6.0
    - pyproj
    - matplotlib-base
    - pyogrio
    - rioxarray
    - scipy
    - numpy
    - pygmt >=0.10.0
    - geopandas
    - zarr
    - python-dotenv
    - nptyping
    - requests

test:
  imports:
    - polartoolkit

about:
  home: https://antarctic-plots.readthedocs.io
  summary: Helpful tools for polar researchers
  license: MIT
  license_file: LICENSE
  doc_url: https://antarctic-plots.readthedocs.io/
  dev_url: https://github.com/mdtanker/polartoolkit

extra:
  recipe-maintainers:
    - mdtanker
