{% set name = "polartoolkit" %}
{% set version = "0.8.1" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polartoolkit-{{ version }}.tar.gz
  sha256: 7244d2c680972c8fea60c9cd2bd9253f4e04b029a50ce894ebd5ae913382d874

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
###
###
###
# RESET BUILD NUMBER
###
###
###
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - openpyxl
    - pooch
    - tqdm
    - verde >=1.8.0
    - xarray
    - harmonica >=0.6.0
    - pyproj
    - rioxarray
    - scipy
    - numpy
    - pygmt >=0.10.0
    - geopandas <1.0
    - zarr
    - python-dotenv
    - requests
    - deprecation
    - earthaccess

test:
  imports:
    - polartoolkit

about:
  home: https://polartoolkit.readthedocs.io
  summary: Helpful tools for polar researchers
  license: MIT
  license_file: LICENSE
  doc_url: https://polartoolkit.readthedocs.io/
  dev_url: https://github.com/mdtanker/polartoolkit

extra:
  recipe-maintainers:
    - mdtanker
