{% set name = "polartoolkit" %}
{% set version = "1.0.3" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polartoolkit-{{ version }}.tar.gz
  sha256: c7fcba6fb0892eaee0d13ffd7ad796a45d16b38871b404d3d472f86fb276e8b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
###
###
###
# RESET BUILD NUMBER
###
###
###
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - openpyxl
    - pooch
    - tqdm
    - verde
    - xarray
    - harmonica >=0.6.0
    - pyproj
    - rioxarray
    - scipy
    - numpy
    - pygmt >=0.10.0
    - geopandas >=1.0
    - pyogrio
    - zarr
    - python-dotenv
    - requests
    - deprecation
    - earthaccess
    - xrft

test:
  imports:
    - polartoolkit

about:
  home: https://polartoolkit.readthedocs.io
  summary: Helpful tools for polar researchers
  license: MIT
  license_file: LICENSE
  doc_url: https://polartoolkit.readthedocs.io/
  dev_url: https://github.com/mdtanker/polartoolkit

extra:
  recipe-maintainers:
    - mdtanker
