{% set name = "polartoolkit" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polartoolkit-{{ version }}.tar.gz
  sha256: 8ce8902f357d2ebb83f1027143544a77df6c09594d375ce75e665a7df7eaf9df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
###
###
###
# RESET BUILD NUMBER
###
###
###
requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - pip
  run:
    - python >=3.9
    - pandas
    - openpyxl
    - pooch
    - tqdm
    - verde >=1.8.0
    - xarray
    - harmonica >=0.6.0
    - pyproj
    - matplotlib-base
    - pyogrio
    - rioxarray
    - scipy
    - numpy
    - pygmt >=0.10.0
    - geopandas <1.0
    - zarr
    - python-dotenv
    - requests
    - deprecation
    - earthaccess

test:
  imports:
    - polartoolkit

about:
  home: https://polartoolkit.readthedocs.io
  summary: Helpful tools for polar researchers
  license: MIT
  license_file: LICENSE
  doc_url: https://polartoolkit.readthedocs.io/
  dev_url: https://github.com/mdtanker/polartoolkit

extra:
  recipe-maintainers:
    - mdtanker
