{% set name = "polartoolkit" %}
{% set version = "1.5.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polartoolkit-{{ version }}.tar.gz
  sha256: 39a989c5b0540c2be660cf0dd6a7be08e6ec7fbdeb70ef347c88079c7d76bbb5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.0
    - pandas >=2.0.0
    - xarray >=2023.4.0
    - netcdf4 >=1.6.0
    - h5netcdf >=1.5.0
    - scipy >=1.11.0
    - verde
    - pooch
    - rioxarray
    - tqdm
    - pygmt >=0.10.0
    - harmonica >=0.6.0
    - deprecation
    - openpyxl
    - pyproj
    - geopandas >=1.0
    - pyogrio
    - zarr >=3.0
    - python-dotenv
    - requests
    - earthaccess
    - xrft
    - scooby
test:
  imports:
    - polartoolkit

about:
  home: https://polartoolkit.readthedocs.io
  summary: Helpful tools for polar researchers
  license: MIT
  license_file: LICENSE
  doc_url: https://polartoolkit.readthedocs.io/
  dev_url: https://github.com/mdtanker/polartoolkit

extra:
  recipe-maintainers:
    - mdtanker
